### ISSUE TITLE
Não recebo o email com o alerta do evento.

### ISSUE THREAD

**Issue by 18vamberto** [sansaoipb/Graphical_notifications_Zabbix#1]
![2023-02-20_162103](https://user-images.githubusercontent.com/111987531/220185258-b28a474e-e8d8-45e3-844e-5e2119264e8d.jpg)
![2023-02-20_162117](https://user-images.githubusercontent.com/111987531/220185260-88266104-d6f5-4b7a-94e1-5c47c57107e5.jpg)
![2023-02-20_162128](https://user-images.githubusercontent.com/111987531/220185262-5a7ebac3-7862-4a60-a0c4-aa3ee5a7337f.jpg)

Boatarde.

Estou tentando usar no zabbix 6.0.13 somente e-mail, fiz toda configuração, ao fazer esse teste pelo meu linux (sudo -u zabbix ./notificacoes-teste.py --send "-123456789, 5522988776655, usuario@provedor.com") chego a receber um um email com um grafico, ao fazer o teste de midia no zabbix aparentemente da certo so que não recebo nenhum email do teste, acessando o diretorio cd /usr/lib/zabbix/alertscripts/log e vendo o log gerado em (notificacoes.log) me deparo com essa mensagem **[2023-02-20 16:00:14,427][ERROR] - not enough values to unpack (expected 5, got 1) >> at split (triggerid, eventid, color, period, body) | Quantidade de argumentos in$$tos insuficientes no split (triggerid, eventid, color, period, body)** no log. no zabbix na parte de incidente aparece como enviado o meu incidente para o e-mail que configurei mas não chega nenhum e-mail, pode me dar uma direção quanto ao que pode ser?

att.:

Estou anexando algumas imgens da configuração do tipo de midia.``

**Comment by sansaoipb** [comment]
Prezado, bom dia.
Existe um grupo de ajuda no Telegram para auxiliar melhor os problemas, fica na primeira linha do README.
Mas sua terceira macro está errada, vc copiou e colou o "SUBJECT" e não editou, realizando o ajuste ele vai considerar a mensagem.
Caso não tenha sucesso, entre no grupo para tratarmos mais próximo e com detalhes.
