### ISSUE TITLE
Configuração do script para enviar gráfico de monitoramento web.

### ISSUE THREAD

**Issue by alancdias7** [sansaoipb/Graphical_notifications_Zabbix#1]
Bom dia, 

Poderiam me auxiliar na configuração do script?

Estou utilizando o Ubuntu 18.04 com Zabbix 5.2.

A intenção inicial é apenas monitorar páginas web e enviar alertas parar para o Telegram, contudo, gostaria que os gráficos também fossem enviados.

Configurei utilizando "Web Scenarios", o "Actions" executa, mas falha no envio.

![image](https://user-images.githubusercontent.com/53276043/103102005-d99bbb80-45f8-11eb-9c69-8231379eaac8.png)

![image](https://user-images.githubusercontent.com/53276043/103102012-e8826e00-45f8-11eb-8c4a-7f97765c9223.png)

Obs. Realizando os testes, através do shell, funciona.

Configuração Media Types.

![image](https://user-images.githubusercontent.com/53276043/103102068-25e6fb80-45f9-11eb-8b8f-9ed9751223f7.png)

![image](https://user-images.githubusercontent.com/53276043/103102081-2ed7cd00-45f9-11eb-9aec-8a0f0de2ce33.png)

![image](https://user-images.githubusercontent.com/53276043/103102120-5333a980-45f9-11eb-8c6d-3a8239ac7490.png)

**Comment by sansaoipb** [comment]
Boa tarde. 
Vc colocou as macros na ordem errada no tipo de mídia. 
Reveja o git, e se tiver dificuldades entre no grupo de ajuda informado no início do how to
