### ISSUE TITLE
Problema com envio/configuração

### ISSUE THREAD

**Issue by Meephz** [sansaoipb/Graphical_notifications_Zabbix#2]
Bom dia, estou com o seguinte erro ao usar o comando

Seria alguma atualização que houve com o pyrogram?

sudo -u zabbix ./notificacoes-teste.py --info "-100xxxxxx"

Traceback (most recent call last):
  File "/usr/lib/zabbix/alertscripts/./notificacoes-teste.py", line 42, in <module>
    from pyrogram.raw.functions.channels import GetForumTopics
ImportError: cannot import name 'GetForumTopics' from 'pyrogram.raw.functions.channels' (/var/lib/zabbix/.local/lib/python3.9/site-packages/pyrogram/raw/functions/channels/__init__.py)

**Comment by sansaoipb** [comment]
Boa tarde.

Sim, houve uma atualização no pyrogram que foi debatido no grupo de ajuda, que oriento fortemente a participação até para tratar esses problemas e todos se ajudarem mutuamente.

Tente resolver executando o comando:
**sudo -u zabbix python3 -m pip install --upgrade pyrogram**

Caso não resolva, entre no grupo de ajuda que consta na primeira linha do README para ter uma ajuda mais próxima e rápida.
