### ISSUE TITLE
cor do background

### ISSUE THREAD

**Issue by joel-vasiliev** [sansaoipb/Graphical_notifications_Zabbix#2]
primeiramente parabéns pelo projeto, ficou muito bom!
gostaria de saber se é possível alterar a cor do background do gráfico

**Comment by sansaoipb** [comment]
Obrigado @joel-vasiliev.
O background, e com base no tema do zabbix, então se estiver usando um tema claro, o fundo virá claro, se mudar para escuro virá preto.
