### ISSUE TITLE
Falha ao executar o teste com whatsapp

### ISSUE THREAD

**Issue by marcilioramos** [sansaoipb/Graphical_notifications_Zabbix#3]
Fala meu querido.

Fui realizar um teste com whatsapp e apresentou um erro:

"No option 'acess.codekey' in section: 'PathSectionWhatsApp'"

acessei o codigo e alterei a linha 
de:
acessKey0 = PropertiesReaderX(path.format('configScripts.properties')).getValue('PathSectionWhatsApp', 'acess.codekey')
para:
acessKey0 = PropertiesReaderX(path.format('configScripts.properties')).getValue('PathSectionWhatsApp', 'acess.key')

**Comment by sansaoipb** [comment]
Aplicado a correção, obrigado pela indicação.
