### ISSUE TITLE
No teste funciona...

### ISSUE THREAD

**Issue by rjwalterbrazolin** [sansaoipb/Graphical_notifications_Zabbix#3]
Quando colocado no zabbix o script dá erro de envio.

Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/notificacoes.py", line 33, in
from pyrogram import Client
ImportError: cannot import name 'Client'

![image](https://user-images.githubusercontent.com/89041496/129619421-73e1e48a-91bd-4995-a690-83973df51541.png)

**Comment by sansaoipb** [comment]
Boa noite.

Os pacotes podem ter sido instalados para root e vc ter executado o teste como root, por isso vai.
O Server usa o usuário zabbix e o pacote precisa estar instalado nele e ser executado como zabbix para fazer o envio.

Entre no grupo de ajuda que está no how to do git para melhor auxilio.


![image](https://user-images.githubusercontent.com/17461376/129629513-f6cf4567-b948-4187-a59e-8ab8224ede43.png)
