### ISSUE TITLE
Error after updating to zabbix 6.4.0

### ISSUE THREAD

**Issue by marspbx** [sansaoipb/Graphical_notifications_Zabbix#4]
Hello everyone, I would like to know if you can help me, I configured the script in my environment and it was working very well for sending email and telegram notifications in the zabbix 6.0.2 version, but I updated the zabbix 6.4.0 version and it stopped working , I get this error in the logs

--------
[2023-11-30 19:19:08,371][ERROR] - Zabbix: Invalid parameter "/": unexpected parameter "user".
[2023-11-30 19:30:16,582][ERROR] - not enough values to unpack (expected 5, got 1) >> at split (triggerid, eventid, color, period, body) | Quantidade de argumentos insuficientes no split (triggerid, eventid, color, period, body)
--------

Has anyone ever caught this error, can you help me?

**Comment by sansaoipb** [comment]
Boa noite Marcelo.
São 2 erros distintos, o primeiro já foi resolvido através atualização do script.

O segundo está relacionado a um erro de configuração, quer dizer que sua mensagem no tipo de mídia/ação 
Não está com linha obrigatória. 

Caso não resolva, existe um grupo de ajuda que está no primeiro parágrafo do git, mas vou deixar o link também aqui.

https://t.me/+bTDzmSmMPHYzOTJh

Que seja não somente para ajuda, mas para sugestões de melhorias e de acompanhamentos dos problemas e soluções.

**Comment by marspbx** [comment]
Opa Bom dia!,


A sim perfeito, não havia visto a atualização, vou pegar a nova versão e realizar os testes, vou entrar no grupo de teletram para participar com vocês.


Obrigado!
